[[queries]]
chain = 1
desc = "Transactions by Account Address"
events = []
sql = """
select
  block_timestamp::date,
  hash,
  "to",
  substring(input, 1, 4) as "4b"
from txs
where "from" = 0xd8da6bf26964af9d7eed9e03e53415d37aa96045
"""

[[queries]]
chain = 1
desc = "Nested Tuples: Morpho Blue Market Creation"
events = [
    "CreateMarket(bytes32 indexed id, (address loanToken, address collateralToken, address oracle, address irm, uint256 lltv) marketParams)",
]
sql = """
select
  id,
  marketParams->>'loanToken' as loan_token,
  marketParams->>'collateralToken' as collateral,
  marketParams->>'lltv' as lltv
from createmarket
where address = 0xBBBBBbbBBb9cC5e90e3b3Af64bdAF62C37EEFFCb
order by block_num desc
limit 100
"""

[[queries]]
chain = 1
desc = "SUM/CASE: ERC20 Transfers Sent/Received per Token"
events = ["Transfer(address indexed from, address indexed to, uint256 value)"]
sql = """
select
  address token,
  sum(
    case
    when "from" = 0xd8da6bf26964af9d7eed9e03e53415d37aa96045
    then 1
    else 0
    end
  ) sent,
  sum(
    case
    when "to" = 0xd8da6bf26964af9d7eed9e03e53415d37aa96045
    then 1
    else 0
    end
  ) received
from transfer
where (
  "to" = 0xd8da6bf26964af9d7eed9e03e53415d37aa96045
  or "from" = 0xd8da6bf26964af9d7eed9e03e53415d37aa96045
)
and block_num > 25300000
group by token
order by 2 desc, 3 desc
limit 25
"""

[[queries]]
chain = 1
desc = "ARRAYS: ERC-1155 Transfer Batch"
events = [
    "TransferBatch(address indexed operator, address indexed from, address indexed to, uint256[] ids, uint256[] amounts)",
]
sql = """
select
  log_idx,
  "from",
  "to",
  ids,
  amounts
from transferbatch
where block_num = 25444605
and log_idx = 607
"""

[[queries]]
chain = 1
desc = "COUNT/DISTINCT: Unique Senders/Receivers of ERC-721 Transfers per Block"
events = [
    "Transfer(address indexed from, address indexed to, uint indexed tokenId)",
]
sql = """
select
  block_num,
  count(distinct(tx_hash)) transactions,
  count(distinct("from")) senders,
  count(distinct("to")) receivers
from transfer
group by block_num
order by block_num desc
limit 1
"""

[[queries]]
chain = 1
desc = "SELF JOIN: Recent Nouns Token Holders"
events = [
    "Transfer(address indexed from, address indexed to, uint indexed tokenId)",
]
sql = """
select t1."to", t1.tokenId, t1.block_num
from transfer t1
left join transfer t2
on t1.tokenId = t2.tokenId
and t1.block_num < t2.block_num
and t1.address = t2.address
where t1.address = 0x9C8fF314C9Bc7F6e59A9d9225Fb22946427eDC03
and t1.block_num > 25300000
and t2.tokenId is null
order by t1.block_num desc
"""

[[queries]]
chain = 1
desc = "Fun: ENS Name Registrations"
events = [
    "NameRegistered(string name, bytes32 indexed label, address indexed owner, uint256 baseCost, uint256 premium, uint256 expires)",
]
sql = """
select
    tx_hash,
    name,
    owner
from nameregistered
where address = 0x253553366Da8546fC250F225fe3d25d0C782303b
order by block_num desc
limit 100
"""
